config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  resources :users, except: [:index], param: :username
  resources :topics do
    resources :posts
  end
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login',  to: 'sessions#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic

  # validates :content, presence: :true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
  belongs_to :user

  validates :title, presence: :true, length: {maximum: 55}
  validates :image_url, presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :topics

  has_secure_password
  validates :username, presence: true, uniqueness: {case_sensitive: false}
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    if current_user.nil?
      redirect_to root_path, notice: 'You must be logged in to perform this action.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]
  before_action :authorize
  before_action :only_my_posts, only: [:edit, :update]

  def index
    @posts = Post.all.order("created_at ASC")
  end

  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.topic = Topic.find(params[:topic_id])
    if @post.save
      flash[:notice] = "Post success"
      redirect_to topic_path(@post.topic)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post updated'
      redirect_to @post.topic
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to @post.topic
  end

  private
    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :image_url)
    end

    def only_my_posts
      redirect_to @post.topic, notice: 'You may only modify your own posts' if (current_user != @post.user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :layout => false
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now.alert = 'Incorrect email/password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :find_topic, only: [:edit, :show, :destroy]
  before_action :authorize, only: [:new, :edit, :destroy]
  before_action :only_my_topics, only: [:edit, :update, :destroy]

  def index
    @topics = Topic.all.order("updated_at DESC")
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "Thread created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @topic.destroy
    redirect_to root_path
  end

  private
    def find_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title, :content, :image_url)
    end

    def only_my_topics
      redirect_to root_path, notice: 'You may only modify your own posts' if (current_user != @topic.user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]
  before_action :only_my_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
    render :layout => false
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account successfully created"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  def edit
  end

  def update
    if @user.update(params.require(:user).permit(:email, :password, :password_confirmation))
      redirect_to root_path , notice: "Your settings were successfully updated."
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by(username: params[:username])
    @user.destroy
    redirect_to root_path, notice: "Account successfully closed."
  end

  private
    def find_user
      @user = User.find_by(username: params[:username])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :account_level)
    end

    def only_my_user
      redirect_to root_path, notice: "You cannot modify others' accounts" if current_user != @user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def format_datetime(datetime)
    datetime.strftime("%e %B %Y %r")
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <small class='footer-left'><a href='https://www.youtube.com/watch?v=fp-52d4HxtY'>Contact me don't contact me</a></small>
  <small class='footer-right'>The Whiteboard by <a href='http://github.com/chinibi'>Trevor Pham</a></small>
</footer>

app/views/layouts/_header.html.erb
<header id='navbar' class='navbar navbar-inverse navbar-fixed-top'>
  <div class='container'>
    <nav>
      <ul class='nav navbar-nav navbar-left'>
        <li><%= link_to "Whiteboard", root_path, id:'home-button' %></li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if current_user %>
          <li>
            <%= link_to current_user.username, user_path(current_user.username) %>
          </li>
          <li>
            <%= link_to 'Log out', session_path('dummy'), method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Create Account', new_user_path, 'data-toggle' => 'modal', 'data-target' => '#signup-modal'%>
          </li>
          <li>
            <%= link_to 'Log In', login_path, 'data-toggle' => 'modal', 'data-target' => '#login-modal' %>
          </li>
        <% end %>
          <li><%= link_to 'Home', root_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_modal.html.erb
<div class='container'>
  <div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forums</title>
  <link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/modal' %>
  <div class='main container'>
    <%= notice %>
    <%= yield %>
  </div>
  <div class='footer container'>
    <%= render 'layouts/footer' %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>
  // $(window).load(function() {
  //   var $grid = $('.topic.listing')

  //   $grid.imagesLoaded(function() {
  //     $grid.masonry({
  //       itemSelector: '.topic-.isting',
  //       columnWidth: '.topic.listing'
  //     })
  //   })
  // })
  </script>
</body>
</html>

app/views/posts/_form.html.erb
<div class='canvas container'>
  <canvas id='create-canvas' width='400' height='400'></canvas>
</div>

<%= form_for([@topic,@post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Text' %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :image_url, class: "form-control image-url" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<div class='canvas container'>
  <canvas id='create-canvas' width='400' height='400'></canvas>
</div>

<!-- figure out how to DRY this file; it's nearly the same as new.html.erb
except for the form routing -->
<%= form_for([@topic,@post], url: topic_post_path(@post.topic, @post), html: {method: 'patch'}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Text' %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div>
    <%= f.hidden_field :image_url, class: "image-url" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Create post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<div class='create-content'>
  <%= link_to "New Thread", new_topic_path %>
</div>
<div id='thread-list'>
  <% @topics.each do |topic| %>
  <div class='col-lg-3 col-md-4 col-sm-6 col-xs-12 topic listing'>
    <div class='inner-topic panel'>
      <img class='img-responsive thumbnail' src=<%= topic.image_url %>>
      <p class='title'>
        <%= link_to topic.title, topic_path(topic), title: topic.title %>
      </p>
      <small>
        by <%= link_to topic.user.username, user_path(topic.user.username)%>
        <%= time_ago_in_words(topic.created_at) %> ago

        <% if current_user == topic.user %>
          <%= link_to 'Delete', topic_path(topic), method: :delete, data: {confirm: 'Delete this thread?'} %>
        <% end %>
      </small>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<div class='canvas container'>
  <canvas id='create-canvas' width='400' height='400'></canvas>
</div>

<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@topic.errors.count, "error") %> prevented this thread from being created.</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
    <%= f.hidden_field :image_url, class: "form-control image-url" %>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/topics/show.html.erb
<div class='create-content'>
  <%= link_to 'New Post', new_topic_post_path(@topic) %>
</div>

<div class='row' id='posts'>
  <div class='panel post-listing'>
    <p><%= link_to @topic.user.username, user_path(@topic.user.username) %> <%= time_ago_in_words(@topic.created_at) %> ago</p>
    <div>
      <img src=<%= @topic.image_url%>>
      <p class='post-text'><%= @topic.content %></p>
    </div>
  </div>

  <% @topic.posts.order("created_at ASC").each do |post| %>
    <div class='panel post-listing'>
      <p>
        <%= link_to post.user.username, user_path(post.user.username) %> <%= time_ago_in_words(post.created_at) %> ago
        <% if current_user == post.user %>
          <%= link_to 'Edit', edit_topic_post_path(@topic, post) %>
          <%= link_to 'Delete', topic_post_path(@topic, post), method: :delete, data: {confirm: 'delete this post?'} %>
        <% end %>
      </p>
      <div class='img-container'>
        <img class='img-responsive' src=<%= post.image_url %>>
      </div>
      <p class='post-text'><%= post.content %></p>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit account</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit class: "btn btn-primary" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Create account</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit class: "btn btn-primary" %></div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<table class='table'>
 <tr>
   <td>User ID</td>
   <td><%= @user.id %></td>
 </tr>
 <tr>
   <td>Account created</td>
   <td><%= format_datetime(@user.created_at.in_time_zone(-8)) %></td>
 </tr>
</table>

<%= link_to "Close this account", user_path, method: :delete, data: {confirm: 'Really delete this account?'} %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>